eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://serviceregistry:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
spring:
  zipkin:
    baseUrl: http://localhost:9411
